[project]
name = "visknacks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
license = "BSD-3-Clause"
authors = [
    {name = "Nicholas M. Synovic", email = "nicholas.synovic@gmail.com"},
]
keywords = ["paraview", "mcp", "visualization", "llm", "scientific-visualization"]
classifiers = [
    "Private :: Do Not Upload",
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Environment :: GPU :: NVIDIA CUDA",
    "Framework :: FastAPI",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.10",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Multimedia :: Graphics :: 3D Rendering",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Visualization"
]

[project.urls]
Homepage = "https://github.com/NicholasSynovic/VisKnacks"
Repository = "https://github.com/NicholasSynovic/VisKnacks"
Issues = "https://github.com/NicholasSynovic/VisKnacks/issues"

[project.scripts]
pvpython-renderer-mcp = "pvpython_renderer.main:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 80

[tool.ruff.lint]
ignore = ["F403", "F405"]
